[project]
name = "zelestra-aws-hackathon"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.3",
    "scikit-learn>=1.4.2",
    "lightgbm>=4.3.0",
    "catboost>=1.2.5",
    "joblib",
    "category-encoders>=2.8.1",
]
